# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[default]
src = 'src'
test = 'test'
out = 'dist'
libs = ['lib']

[example]
src = 'example_simple'
test = 'example_simple'
